name: tests

on: push

jobs:
  cover_tests:
    name: Cover Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Lint
      run: npx standard

    - name: Cover Tests
      run:
        npm run test:cover
      env:
        STRESS: true
      
    - name: RunConnect Testnet Tests
      if: false
      run:
        npm run test:cover test/kernel/blockchain.js
      env: 
        API: run
        NETWORK: test
        STRESS: true
        CLEAN: false
        PURSE_TEST: ${{ secrets.PURSE_TESTNET }}

    - name: RunConnect Mainnet Tests
      if: false
      run:
        npm run test:cover test/kernel/blockchain.js
      env: 
        API: run
        NETWORK: main
        CLEAN: false
        PURSE_MAIN: ${{ secrets.PURSE_MAINNET }}
      continue-on-error: true
      
    - name: WhatsOnChain Testnet Tests
      if: false
      run:
        npm run test:cover test/kernel/blockchain.js
      env: 
        API: whatsonchain
        NETWORK: test
        STRESS: true
        CLEAN: false
        PURSE_TEST: ${{ secrets.PURSE_TESTNET2 }}

    - name: PayServer Testnet Tests
      if: false
      run:
        npm run test:cover test/plugins/pay-server.js
      env: 
        API: run
        NETWORK: test
        CLEAN: false

    - name: StateServer Mainnet Tests
      if: false
      run:
        npm run test:cover test/plugins/state-server.js
      env: 
        API: run
        NETWORK: main
        CLEAN: false

    - name: Publish Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
        slug: JeffersonKernel/run-sdk

  node_10_tests:
    name: Node 16 Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Test Node
      run: npm run test:node

  node_12_tests:
    name: Node 18 Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 18
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Test Node
      run: npm run test:node

  node_16_tests:
    name: Node 20 Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 20
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Test Node
      run: npm run test:node

  firefox_tests:
    name: Firefox Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Test Firefox
      run: env BROWSER=firefox npm run test:browser

  chrome_tests:
    name: Chrome Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Test Chrome
      run: env BROWSER=chrome npm run test:browser

  edge_tests:
    name: Edge Tests
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci
      shell: bash

    - name: Test Edge
      run: env BROWSER=MicrosoftEdge npm run test:browser
      shell: bash
      